name: CI/CD Pipeline

on:
  push:
    branches:
      - main   # roda quando você faz push na branch main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Instalar dependências
        run: npm install

      - name: Rodar testes
        run: npm test

      - name: Build da aplicação
        run: npm run build

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Deploy (simulado)
        run: echo "Aqui você colocaria o comando para deploy (ex: docker, kubectl, vercel, heroku, etc)"