version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: express-crud
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    volumes:
    - pgadmin_data:/var/lib/pgadmin 
    depends_on:
      - postgres
    networks:
      - backend

  api:
    build:
      context: ../../
      dockerfile: Dockerfile
    container_name: express-api
    ports:
      - "3001:3001"
    env_file:
      - ../../.env
    depends_on:
      - postgres
    networks:
      - backend

volumes:
  pgdata:
  pgadmin_data:

networks:
  backend: