version: '3.8'

services:
  db:
    image: postgres:16
    container_name: postgres_todos
    restart: always
    environment:
      POSTGRES_USER: myst1
      POSTGRES_PASSWORD: coxinha123
      POSTGRES_DB: todos
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data: